---
- hosts: dbserver
  become: true
  tasks:
    - name: Ensure MariaDB-server is installed.
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB-server is started and enabled at reboot
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started