---
- hosts: dbserver
  become: true
  collections:
    - community.mysql

  tasks:
    - name: Ensure PyMySQL is installed
      ansible.builtin.package:
        name: python3-PyMySQL
        state: present

    - name: Ensure MariaDB-server is installed.
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB-server is started and enabled at reboot
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started
    
    - name: Create a new database with name 'webappdb'
      community.mysql.mysql_db:
        name: webappdb
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
    
    - name: Create user 'webappuser' with priviliges
      community.mysql.mysql_user:
        name: webappuser
        password: secretpassword
        priv: "webappdb.*:ALL"
        host: localhost
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock